#!/bin/bash
#
# Copy to daemonize and edit.

HOME=/path/to/home
SC_VIRTUALENV="$HOME/.virtualenvs/suttacentral"
SC_ROOT="$HOME/suttacentral"

source "$SC_VIRTUALENV/bin/activate"
cd "$SC_ROOT"
exec invoke server
