all:
	./pass1.py
	./pass2.py
	./pass3.py
	./dn.py
	./mn.py

clean:
	rm -rf tmp output

assets:
	cp tmp/sc.css output/mn
	cp tmp/sc.css output/dn
	cp ../../static/fonts/tharlon-regular-1.ttf output/mn
	cp ../../static/fonts/tharlon-regular-1.ttf output/dn
