blurbs = {
"en": {
"dn": "The Long Discourses",
"mn": "The Medium Length Discourses",
"sn": "The Connected Discourses",
"an": "The Numerical Discourses",
"kn": "The Small Discourses",
"an3.1": "Fools are dangerous, but the wise are safe.",
"an3.2": "Marks of a fool and an astute person: body, speech, and mind.",
"an3.3": "Marks of a fool and an astute person: thinking, speaking, and doing.",
"an3.4": "Marks of a fool and an astute person: recognizing mistakes.",
"an3.5": "Marks of a fool and an astute person: asking questions.",
"an3.6": "Marks of a fool and an astute person: wholesome and unwholesome.",
"an3.7": "Marks of a fool and an astute person: blameworthy and blameless.",
"an3.8": "Marks of a fool and an astute person: hurtful and kind.",
"an3.9": "Marks of a fool and an astute person: keeping your mind healthy.",
"an3.10": "Immorality, envy, and meanness determine rebirth.",
"an3.11": "What well-known mendicants should encourage.",
"an3.12": "Places that should be commemorated by kings and mendicants.",
"an3.13": "People who are hopeless, hopeful, and have done away with hope.",
"an3.14": "Wheel-turning Monarchs and Buddhas both rely on principle as authority.",
"an3.15": "Quality takes time: the parable of the chariot-maker.",
"an3.16": "Practices that can’t fail.",
"an3.17": "Hurting yourself and others.",
"an3.18": "Spiritual practice isn’t for rebirth in heaven.",
"an3.19": "Shopkeepers and mendicants both have to work hard.",
"an3.20": "Shopkeepers and mendicants both have to be clever, responsible, and well supported.",
"an3.21": "Of various individuals on the path, which is best?",
"an3.22": "Healing the body, healing the mind. Everyone should be treated, even if they don’t recover.",
"an3.23": "Hurtful or pleasing choices lead to hurtful or pleasing experiences in future lives.",
"an3.24": "Three people who are very helpful.",
"an3.25": "A mind like an open sore, like lightning, and like a diamond.",
"an3.26": "You should associate with people who are equal or better than you.",
"an3.27": "Who to associate with, and who to shun.",
"an3.28": "Speech like dung, like flowers, and like honey.",
"an3.29": "Being spiritually blind, one-eyed, or with two eyes.",
"an3.30": "How to make the wisdom of hearing Dharma last when the talk is over.",
"an3.31": "Parents should be honoured like Brahmā.",
"an3.32": "Could there be a state of convergence with no sense of self?",
"an3.33": "Even the Buddha found it hard to get students to understand.",
"an3.34": "Greed, hate, and delusion, and their opposites, are like seeds.",
"an3.35": "The Buddha sleeps well, even on the cold, hard ground.",
"an3.36": "The god of death questions us, but we are punished by our own deeds.",
"an3.37": "The gods rejoice when they see people practising well.",
"an3.38": "One should aspire to be like an awakened mendicant, not like Sakka.",
"an3.39": "Siddhattha’s delicate upbringing.",
"an3.40": "Practising with yourself in charge, or with others, or the teaching.",
"an3.41": "Factors in making good karma.",
"an3.42": "How to know a faithful person.",
"an3.43": "The advantages of teaching Dharma.",
"an3.44": "Teachers and audience should have understanding.",
"an3.45": "Giving, going forth, and caring for parents are praised.",
"an3.46": "Villagers make good karma when good mendicants are there.",
"an3.47": "The difference between conditioned and unconditioned.",
"an3.48": "A family is supported by their head, as a tree is supported by a mountain.",
"an3.49": "Being keen in three ways.",
"an3.50": "Why a mendicant is like a thief.",
"an3.51": "You can begin to practice even late in life: advice to elderly brahmins.",
"an3.52": "You can begin to practice even late in life: advice to elderly brahmins.",
"an3.53": "How is the teaching realizable in this very life?",
"an3.54": "How is the teaching realizable in this very life?",
"an3.55": "How is extinguishment realizable in this very life?",
"an3.56": "Why has the world become depopulated?",
"an3.57": "The Buddha is accused of soliciting gifts for his community only.",
"an3.58": "A master of Vedic knowledge in the brahmanical system and in the Buddha’s.",
"an3.59": "A master of Vedic knowledge in the brahmanical system and in the Buddha’s.",
"an3.60": "A brahmin argues that a sacrifice is less selfish than the mendicant’s life. And the king’s men are deploring the decline in psychic abilities among the Saṅgha.",
"an3.61": "The beliefs that everything is caused by past karma, by a creator God, or by chance all lead to inaction. The Buddha teaches dependent origination.",
"an3.62": "Perils that tear mothers and children apart.",
"an3.63": "The high and luxurious beds that the Buddha uses.",
"an3.64": "A recently disrobed monk boasts of knowing everything about the Buddha’s teaching.",
"an3.65": "How to navigate among different spiritual opinions.",
"an3.66": "How to navigate among different spiritual opinions.",
"an3.67": "Assessing whether someone is fit to hold a discussion.",
"an3.68": "The differences between greed, hate, and delusion.",
"an3.69": "Unwholesome roots create unwholesome actions, and lead to suffering.",
"an3.70": "The uposatha observance day of the cowherds, the Jains, and the Buddha.",
"an3.71": "Why should we give up greed, hate, and delusion?",
"an3.72": "Who has good teaching and practice?",
"an3.73": "Does convergence come first, or knowledge?",
"an3.74": "Do we purify ourselves by wearing out old karma?",
"an3.75": "How to encourage and support those close to you.",
"an3.76": "How consciousness, karma, and craving create and sustain future lives.",
"an3.77": "How consciousness, karma, and craving create and sustain future lives, with an emphasis on intention.",
"an3.78": "Not all spiritual paths are of equal value.",
"an3.79": "Some fragrances spread even against the wind.",
"an3.80": "Ānanda gets the Buddha to talk about the scale of the universe.",
"an3.81": "The duties of an ascetic.",
"an3.82": "A donkey tries to moo like a cow. It doesn’t end well.",
"an3.83": "The duties of a farmer are like those of a mendicant.",
"an3.84": "What to do if you can’t keep all the rules.",
"an3.85": "What exactly is a “trainee”?",
"an3.86": "Even spiritually advanced people can break minor rules.",
"an3.87": "Even spiritually advanced people can break minor rules.",
"an3.88": "Even spiritually advanced people can break minor rules.",
"an3.89": "The three trainings explained, to seeing the truths.",
"an3.90": "The three trainings explained, to perfection.",
"an3.91": "A monk is critical of the Buddha, but later feels remorse.",
"an3.92": "Neither a farmer or a mendicant makes their work bear fruit any faster just by wishing for it.",
"an3.93": "Seclusion as depicted in other paths and by the Buddha.",
"an3.94": "The clarity of stream-entry is like a cloudless spring sky.",
"an3.95": "Assemblies that are the best, or divided, or harmonious. A harmonious assembly lead the mind to happiness and stillness.",
"an3.96": "A mendicant is beautiful, strong, and fast like a thoroughbred horse: to seeing the truths.",
"an3.97": "A mendicant is beautiful, strong, and fast like a thoroughbred horse: to non-return.",
"an3.98": "A mendicant is beautiful, strong, and fast like a thoroughbred horse: to perfection.",
"an3.99": "A bad mendicant is ugly and rough like jute canvas.",
"an3.100": "If deeds were experienced exactly as performed, there could be no spiritual practice.",
"an3.101": "Meditation is like purifying gold. A meditator should progressively eliminate more refined corruptions.",
"an3.102": "Meditation is like purifying gold. A meditator should focus on different aspects at different times in order to proceed smoothly.",
"an3.103": "Before awakening, Siddhattha reflected on gratification, danger and escape in the world.",
"an3.104": "The Buddha became awakened by understanding gratification, danger and escape.",
"an3.105": "Gratification, danger and escape are essential to both binding and freeing.",
"an3.106": "Real ascetics understand gratification, danger and escape.",
"an3.107": "Song, dance, and laughter.",
"an3.108": "Indulgences never satisfy.",
"an3.109": "Protecting your mind is like protecting a house.",
"an3.110": "A simile of a collapsing house.",
"an3.111": "Sources of deeds: greed, hate, and delusion.",
"an3.112": "Sources of deeds: past, present, future.",
"an3.113": "Hypocrisy leads to downfall.",
"an3.114": "Three people hard to find.",
"an3.115": "People who are easy to measure, hard to measure, and immeasurable.",
"an3.116": "Rebirth in the formless realms, for ordinary people and for disciples of the Buddha.",
"an3.117": "Failure or success in morality, mind, and view.",
"an3.118": "Failure or success in morality, mind, and view is like loaded dice.",
"an3.119": "Failure or success in action, livelihood, and view.",
"an3.120": "Purity of body, speech, and mind.",
"an3.121": "Purity of body, speech, and mind, with understanding the five hindrances.",
"an3.122": "Sagacity of body, speech, and mind.",
"an3.123": "What a mendicant thinks about the food they’re offered.",
"an3.124": "When mendicants fight, the Buddha doesn’t like it.",
"an3.125": "The Buddha teaches a simple but powerful message: his teaching is from personal experience, and it works.",
"an3.126": "The Buddha discusses different kinds of teachers while staying at a hermitage near his home town of Kapilavatthu.",
"an3.127": "A god from the Pure Abodes visits the Buddha, and complains about how busy he is.",
"an3.128": "The Buddha helps a monk in distress by teaching of “bitterness”, “rotting flesh”, and “flies”.",
"an3.129": "Anuruddha asks the Buddha what leads women to bad rebirth.",
"an3.130": "Anuruddha complains of not being awakened.",
"an3.131": "Three things shine in the open: the moon, the sun, and the teachings of the Buddha.",
"an3.132": "A line drawn in stone, sand, or water.",
"an3.133": "Three ways a mendicant is like a king’s warrior.",
"an3.134": "Educated in fancy talk, in questioning, or to the fullest extent.",
"an3.135": "A good friend does what’s hard.",
"an3.136": "Impermanence, suffering, and not-self are natural laws discovered by the Buddha.",
"an3.137": "The teacher called Makkhali is the worst of all, like a hair blanket.",
"an3.138": "Success in faith, morality, and wisdom.",
"an3.139": "Growth in faith, morality, and wisdom.",
"an3.140": "Training people is like training wild horses.",
"an3.141": "Training people is like training good horses.",
"an3.142": "Training people is like training thoroughbred horses.",
"an3.143": "The ultimate end, the ultimate sanctuary, the ultimate spiritual life, the ultimate goal: the three trainings.",
"an3.144": "The ultimate end, the ultimate sanctuary, the ultimate spiritual life, the ultimate goal: the three wonders.",
"an3.145": "The ultimate end, the ultimate sanctuary, the ultimate spiritual life, the ultimate goal: view, knowledge, freedom.",
"an3.146": "Wholesome and unwholesome deeds determine rebirth.",
"an3.147": "Blameless and blameworthy deeds determine rebirth.",
"an3.148": "Ethical and unethical deeds determine rebirth.",
"an3.149": "Pure and impure deeds determine rebirth.",
"an3.150": "Wholesome deeds keep you whole.",
"an3.151": "Blameless deeds keep you whole.",
"an3.152": "Ethical deeds keep you whole.",
"an3.153": "Pure deeds keep you whole.",
"an3.154": "Kinds of homage: body, speech, and mind.",
"an3.155": "A good morning, a good afternoon, a good evening.",
"an3.156": "The addicted practice, the scorching practice, the middle practice.",

"an4.1": "Both the Buddha and his disciples have been reborn for a long time due to ignorance.",
"an4.2": "Without morality, convergence, wisdom, and freedom, one has fallen from the teaching.",
"an4.3": "After reflection, you should criticize those worthy or criticism, and praise those worthy of praise.",
"an4.4": "You harm yourself by acting badly towards parents, the Buddha, and spiritual practitioners.",
"an4.5": "A person who goes with the stream; a person who goes against the stream; a stable person; and one who has crossed over.",
"an4.6": "Learning the texts and getting the point of learning.",
"an4.7": "A monk, nun, laywoman, and layman who light up the Saṅgha.",
"an4.8": "Because of his spiritual attainments and practice, a Buddha is supremely self-confident.",
"an4.9": "Sources of craving for mendicants.",
"an4.10": "The yokes of sensual pleasures, future lives, views, and ignorance.",
"an4.11": "A mendicant gets rid of unwholesome states right away, in whatever posture they happen to be in.",
"an4.12": "Morality and further practice of eliminating hindrances in all postures.",
"an4.13": "The four right efforts: to prevent, to give up, to develop, and to preserve.",
"an4.14": "The endeavors to restrain, to give up, to develop, and to preserve.",
"an4.15": "The foremost in body, sensuality, dominion, and spiritual development.",
"an4.16": "Subtlety of form, feeling, perception, and choices.",
"an4.17": "Making decisions prejudiced by favoritism, hostility, stupidity, and cowardice.",
"an4.18": "Making decisions unprejudiced by favoritism, hostility, stupidity, and cowardice.",
"an4.19": "Making decisions prejudiced and unprejudiced by favoritism, hostility, stupidity, and cowardice.",
"an4.20": "Allocating meals prejudiced by favoritism, hostility, stupidity, and cowardice.",
"an4.21": "Who should the Buddha revere?",
"an4.22": "What qualifies you as a senior.",
"an4.23": "Why the Buddha is called the Realized One.",
"an4.24": "The Buddha knows what can be known, and remains poised in the midst of the world.",
"an4.25": "This spiritual life is lived for the sake of restraint, giving up, fading away, and stopping.",
"an4.26": "Mendicants who are deceivers, stubborn, flatterers, frauds, insolent, and scattered: they are no mendicants of the Buddha.",
"an4.27": "A mendicant should be content with trifles that are easy to get hold of.",
"an4.28": "Contentment with any old robe, alms-food, lodgings, and love of meditation: these are ancient traditions of the noble ones.",
"an4.29": "Contentment, good will, mindfulness and convergence are basic principles.",
"an4.30": "A discussion with some wanderers on the basic principles.",
"an4.31": "Living in a suitable region, relying on good people, right determination, and past good karma.",
"an4.32": "Inclusiveness through giving, kind speech, taking care, and impartiality.",
"an4.33": "A lion’s roar terrifies beasts. The Buddha’s teaching terrifies the gods.",
"an4.34": "Confidence in the Buddha, the path, the Dharma, and the Saṅgha are the best kinds of confidence.",
"an4.35": "A great man as understood by brahmins and by the Buddha.",
"an4.36": "The brahmin Doṇa is filled with wonder when he sees the Buddha’s footprints.",
"an4.37": "A mendicant who has morality, guards the sense doors, eats in moderation, and is committed to wakefulness can’t decline.",
"an4.38": "A mendicant has eliminated idiosyncratic interpretations of the truth, has totally given up searching, has tranquilized bodily activity, and is said to be ‘withdrawn’.",
"an4.39": "The Buddha criticizes violent sacrifice, but not non-violent giving.",
"an4.40": "The Buddha criticizes violent sacrifice, but not non-violent giving.",
"an4.41": "Developing convergence for pleasure, understanding, mindfulness, and ending defilements.",
"an4.42": "Answering questions definitively, analytically, with a counter-question, or setting it aside.",
"an4.43": "Valuing anger, or denigration, or material possessions, or honor, or valuing the true teaching.",
"an4.44": "Valuing anger, or denigration, or material possessions, or honor, or valuing the true teaching.",
"an4.45": "The god Rohitassa tells how he tried to go to the end of the world.",
"an4.46": "The Buddha relates the story of Rohitassa.",
"an4.47": "The sky and earth and very far apart. What’s further apart?",
"an4.48": "The Buddha praises the teaching of the monk Visākha.",
"an4.49": "Distortions of perception, mind, and view.",
"an4.50": "Four things obscure the sun and moon, so they don’t shine and glow and radiate. And four things corrupt mendicants: alcohol, sex, money, wrong livelihood.",
"an4.51": "When a mendicant meditates using an offering, merit overflows for the donor.",
"an4.52": "When a mendicant has confidence and morality, merit overflows for the donor.",
"an4.53": "Living with gods and zombies.",
"an4.54": "Living with gods and zombies.",
"an4.55": "How a married couple can stay together in this life and the next.",
"an4.56": "How a married couple can stay together in this life and the next.",
"an4.57": "Long life, beauty, happiness, and strength.",
"an4.58": "Long life, beauty, happiness, and strength.",
"an4.59": "Long life, beauty, happiness, and strength.",
"an4.60": "A lay disciple serves the mendicant Saṅgha with robes, alms-food, lodgings, and medicines.",
"an4.61": "Four things that are desirable, but hard to get; and how to get them through deeds of substance.",
"an4.62": "The happiness of ownership, using wealth, debtlessness, and blamelessness.",
"an4.63": "A family where the children honor their parents in their home is said to live with Brahmā.",
"an4.64": "Breaking precepts leads to hell.",
"an4.65": "Estimating others based on appearance, voice, austerity, and principle.",
"an4.66": "The greedy, the hateful, the delusional, and the conceited.",
"an4.67": "Spreading loving-kindness to snakes and other creatures.",
"an4.68": "Possessions, honor, and popularity came to Devadatta for his own ruin and downfall.",
"an4.69": "The endeavors to restrain, to give up, to develop, and to preserve.",
"an4.70": "Corruption of the realm follows corruption of the king.",
"an4.71": "Unfailing practices: morality, learning, energy, and wisdom.",
"an4.72": "Unfailing practices: thoughts of renunciation, good will, and kindness; and right view.",
"an4.73": "Speaking well and ill of others.",
"an4.74": "The best morality, convergence, wisdom, and freedom.",
"an4.75": "The best form, feeling, perception, and state of existence.",
"an4.76": "As he lay dying, the Buddha encouraged his disciples to ask any last questions.",
"an4.77": "If you try to think about these things you will go mad or get frustrated.",
"an4.78": "Four ways of purifying an offering to a teacher.",
"an4.79": "Why for different people the same kind of business undertaking might fail or succeed.",
"an4.80": "Ānanda asks the Buddha why females don’t attend council meetings, undertake business, or travel to Persia.",
"an4.81": "Precepts lead to heaven or hell.",
"an4.82": "Wrong or right speech leads to heaven or hell.",
"an4.83": "Criticizing and praising leads to heaven or hell.",
"an4.84": "Valuing defilements above the Dharma leads to hell.",
"an4.85": "The dark bound for darkness, the dark bound for light, the light bound for darkness, and the light bound for light.",
"an4.86": "One sunk low who sinks lower, one sunk low who rises high, one risen high who sinks low, and one risen high who rises higher.",
"an4.87": "The confirmed ascetic, the white lotus ascetic, the pink lotus ascetic, and the refined ascetic of ascetics.",
"an4.88": "The confirmed ascetic, the white lotus ascetic, the pink lotus ascetic, and the refined ascetic of ascetics.",
"an4.89": "The confirmed ascetic, the white lotus ascetic, the pink lotus ascetic, and the refined ascetic of ascetics.",
"an4.90": "The confirmed ascetic, the white lotus ascetic, the pink lotus ascetic, and the refined ascetic of ascetics.",
"an4.91": "Demons and gods.",
"an4.92": "Serenity and discernment.",
"an4.93": "Serenity and discernment should be developed.",
"an4.94": "To develop serenity and discernment, you should ask experienced practitioners.",
"an4.95": "Practice to help yourself and others.",
"an4.96": "Practice to help yourself and others.",
"an4.97": "Practice to help yourself and others.",
"an4.98": "Practice to help yourself and others.",
"an4.99": "Practice to help yourself and others.",
"an4.100": "Which is better: appropriate praise and criticism, or equanimity?",
"an4.101": "Four people similar to clouds.",
"an4.102": "Four people similar to clouds.",
"an4.103": "Four people similar to pots.",
"an4.104": "Four people similar to ponds.",
"an4.105": "Four people similar to mangoes.",
"an4.106": "",
"an4.107": "Four people similar to mice.",
"an4.108": "Four people similar to oxen.",
"an4.109": "Four people similar to trees.",
"an4.110": "Four people similar to vipers.",
"an4.111": "Guiding people like horses: sometimes, strictly, sometimes gently. And sometimes you have to kill them.",
"an4.112": "A mendicant is like a king’s thoroughbred.",
"an4.113": "A thoroughbred responds when it sees the goad. So does a mendicant.",
"an4.114": "A mendicant is like a king’s elephant.",
"an4.115": "Things that are pleasant or unpleasant, harmful or beneficial.",
"an4.116": "Don’t neglect good conduct.",
"an4.117": "Practice in your own way.",
"an4.118": "Four inspiring places to visit.",
"an4.119": "The perils of birth, old age, sickness, and death.",
"an4.120": "The perils of fire, water, kings, and bandits.",
"an4.121": "The fears of guilt, shame, punishment, and rebirth in a bad place.",
"an4.122": "The risks of waves, crocodiles, whirlpools, and sharks.",
"an4.123": "Length of rebirth in various exalted realms.",
"an4.124": "Contemplating jhānas with wisdom.",
"an4.125": "Rebirth in Brahmā realms from divine abiding meditations.",
"an4.126": "Contemplating divine abiding meditations with wisdom.",
"an4.127": "The Buddha illuminates even interstellar space, so that beings reborn there see each other.",
"an4.128": "Even in a world full of attachment, people listen to the Buddha’s teaching.",
"an4.129": "Monks, nuns, laywomen, and laymen love to hear Dharma from Ānanda.",
"an4.130": "Monks, nuns, laywomen, and laymen love to hear Dharma from Ānanda.",
"an4.131": "People who have given up various fetters.",
"an4.132": "Speaking on topic and fluently.",
"an4.133": "One who understands immediately, one who understands after detailed explanation, one who needs personal guidance, and one who merely learns by rote.",
"an4.134": "Living on the fruit of effort or of past karma.",
"an4.135": "The blameworthy, the mostly blameworthy, the slightly blameworthy, and the blameless.",
"an4.136": "Fulfilling morality, convergence, and wisdom.",
"an4.137": "Valuing morality, convergence, and wisdom.",
"an4.138": "Retreat of body and mind.",
"an4.139": "Good and bad Dharma speakers, and their followings.",
"an4.140": "Having things to say, and saying them well.",
"an4.141": "The brightness of the moon, sun, fire, and wisdom.",
"an4.142": "The radiance of the moon, sun, fire, and wisdom.",
"an4.143": "The lights of the moon, sun, fire, and wisdom.",
"an4.144": "The shining of the moon, sun, fire, and wisdom.",
"an4.145": "The lamps of the moon, sun, fire, and wisdom.",
"an4.146": "A time for listening to the teaching, a time for discussing the teaching, a time for serenity, and a time for discernment.",
"an4.147": "A time for listening to the teaching, a time for discussing the teaching, a time for serenity, and a time for discernment.",
"an4.148": "Speech that’s lying, divisive, harsh, or meaningless.",
"an4.149": "Speech that’s true, harmonious, gentle, and meaningful.",
"an4.150": "Morality, convergence, wisdom, and freedom are essentials.",
"an4.151": "The faculties of faith, energy, mindfulness, and convergence.",
"an4.152": "The powers of faith, energy, mindfulness, and convergence.",
"an4.153": "The powers of wisdom, energy, blamelessness, and inclusiveness.",
"an4.154": "The powers of mindfulness, convergence, blamelessness, and inclusiveness.",
"an4.155": "The powers of reflection, development, blamelessness, and inclusiveness.",
"an4.156": "It’s not easy to measure the length of an eon.",
"an4.157": "Physical health is easier than mental health.",
"an4.158": "Signs of decline: much greed, much hate, and much delusion; and wisdom doesn’t go deep.",
"an4.159": "A nun fakes illness as a pretext to seduce Ānanda.",
"an4.160": "Things that lead to the disappearance of the Dharma.",
"an4.161": "Painful practice with slow insight, painful practice with swift insight, pleasant practice with slow insight, and pleasant practice with swift insight: in brief.",
"an4.162": "Painful practice with slow insight, painful practice with swift insight, pleasant practice with slow insight, and pleasant practice with swift insight: in detail.",
"an4.163": "Painful practice with slow insight, painful practice with swift insight, pleasant practice with slow insight, and pleasant practice with swift insight: in detail.",
"an4.164": "Impatient practice, patient practice, taming practice, and calming practice.",
"an4.165": "Impatient practice, patient practice, taming practice, and calming practice.",
"an4.166": "Painful practice with slow insight, painful practice with swift insight, pleasant practice with slow insight, and pleasant practice with swift insight: which is best?",
"an4.167": "Sāriputta and Moggallāna discuss their practice.",
"an4.168": "Sāriputta and Moggallāna discuss their practice.",
"an4.169": "Getting awakened either with or without extra effort.",
"an4.170": "Ways of practising serenity and discernment.",
"an4.171": "Intention and its results.",
"an4.172": "Sāriputta realized the four kinds of textual analysis a fortnight after he ordained.",
"an4.173": "When the senses end, is there anything left? Or is that just proliferation?",
"an4.174": "When the senses end, is there anything left? Or is that just proliferation?",
"an4.175": "A “terminator” is someone who has made an end of suffering. But are they defined by knowledge or conduct?",
"an4.176": "Leading examples for the four assemblies.",
"an4.177": "A teaching to Rāhula, the Buddha’s son, on the four elements.",
"an4.178": "Meditative attainments don’t always lead to letting go of the attachment to self.",
"an4.179": "Why only some people realize Nirvana in this life.",
"an4.180": "How to determine what is an authentic teaching of the Buddha.",
"an4.181": "How a mendicant is like a warrior.",
"an4.182": "There are some things no-one can guarantee.",
"an4.183": "What we say should never go beyond what we know; but it must also be meanungful.",
"an4.184": "Not everyone is afraid to die.",
"an4.185": "The Buddha redefines the truths of the brahmins.",
"an4.186": "A monk asks a series of questions, which are praised by the Buddha. ",
"an4.187": "The Buddha explains to Vassakāra how only a good person can judge others. Meanwhile, the followers of Todeyya complain about the King.",
"an4.188": "If you criticize someone, you should have a good reason.",
"an4.189": "Different things are realized in different ways.",
"an4.190": "On the Uposatha night, the Buddha praises monks of great spiritual attainments in the Saṅgha.",
"an4.191": "The benefits in the next life of studying Dharma in this life.",
"an4.192": "Ways of assessing a person’s morality, intregity, resilience, and wisdom.",
"an4.193": "The Buddha is accused of using magic to convert followers.",
"an4.194": "Making an effort to be pure in morality, mind, view, and freedom.",
"an4.195": "A discussion with a Jain on whether someone with purified understanding can experience the results of bad karma in the next life.",
"an4.196": "The practice of self-torture doesn’t purify you internally. ",
"an4.197": "Queen Mallikā asks about the karmic causes of beauty, wealth, and power.",
"an4.198": "Those who torture themselves and others, and those who do not.",
"an4.199": "The web of craving that wraps around the self.",
"an4.200": "How love and hate give rise to love and hate; and how one doesn’t fume, ignite, or burn up.",
"an4.201": "A good person keeps precepts—including avoiding alcohol—for themselves, while a better person encourages others as well.",
"an4.202": "A good person has faith and other good qualities, while a better person encourages others to develop these.",
"an4.203": "A good person keeps precepts—including avoiding various kinds of wrong speech—for themselves, while a better person encourages others as well.",
"an4.204": "A good person practices the ten ways of wholesome deeds for themselves, while a better person encourages others as well.",
"an4.205": "A good person practices the eightfold path for themselves, while a better person encourages others as well.",
"an4.206": "A good person practices the tenfold path for themselves, while a better person encourages others as well.",
"an4.207": "It’s good to practice the ten ways of wholesome deeds and to encourage others.",
"an4.208": "It’s good to practice the tenfold path and to encourage others.",
"an4.209": "It’s good character to practice the ten ways of wholesome deeds and to encourage others.",
"an4.210": "It’s good character to practice the tenfold path and to encourage others.",
"an4.211": "Good people light up an assembly.",
"an4.212": "Conduct and view determine rebirth.",
"an4.213": "Conduct and gratitude determine rebirth.",
"an4.214": "Precepts determine rebirth.",
"an4.215": "Initial path factors determine rebirth.",
"an4.216": "Subsequent path factors determine rebirth.",
"an4.217": "Truth and untruth determine rebirth.",
"an4.218": "Truth and untruth determine rebirth.",
"an4.219": "Faith and other qualities determine rebirth.",
"an4.220": "Faith and other qualities determine rebirth.",
"an4.221": "Good speech and bad speech.",
"an4.222": "Things that keep you spiritually healthy, including view.",
"an4.223": "Things that keep you spiritually healthy, including gratitude.",

"an5.1": "Five powers of a trainee.",
"an5.2": "Five powers of a trainee, explained.",
"an5.3": "Suffering in this life and the next.",
"an5.4": "Five qualities determine rebirth.",
"an5.5": "Reasons to criticize a mendicant who disrobes, or praise one who remians.",
"an5.6": "Loss of foundational qualities leads to decline.",
"an5.7": "The Buddha looks after mendicants like a nurse looks after a child until they’ve grown up.",
"an5.8": "A mendicant with five bad qualities fails in the Dharma.",
"an5.9": "A disrespectful mendicant with five bad qualities fails in the Dharma.",
"an5.10": "A mendicant with five bad qualities can’t grow in the Dharma.",
"an5.11": "The five powers of a Realized One.",
"an5.12": "Of the five powers, wisdom is chief.",
"an5.13": "The five powers in brief.",
"an5.14": "The five powers explained in detail.",
"an5.15": "Where to look for the five powers.",
"an5.16": "Wisdom is the chief of the five powers.",
"an5.17": "By practicing but not teaching, one practices for one’s own good.",
"an5.18": "By teaching but not practicing, one practices for the good of both.",
"an5.19": "By neither teaching nor practicing, one doesn’t practice for anyone’ good.",
"an5.20": "By both teaching and practicing, one practice for everyone’s good.",
"an5.21": "If your basic practice is not there, you can’t go higher.",
"an5.22": "If your basic practice is not there, you can’t go higher.",
"an5.23": "The hindrances are like the corruptions in gold.",
"an5.24": "Dharmas starting with morality naturally evolve to freedom.",
"an5.25": "Right view leads to freedom when supported by five factors.",
"an5.26": "Occasions when one can experience liberation.",
"an5.27": "Develop measureless convergence of mind and five knowledges intuitively arise.",
"an5.28": "Five kinds of noble right convergence, including similes.",
"an5.29": "The benefits of walking meditation.",
"an5.30": "The Buddha tells Venerable Nāgita how he dislikes noisy crowds, and wishes never to become famous.",
"an5.31": "Princess Sumanā asks the Buddha about the karmic results of generosity, when other qualities are equal.",
"an5.32": "Princess Cundī asks the Buddha about the best kind of confidence.",
"an5.33": "Uggaha invites the Buddha for a meal, and asks him to advise his daughters, who about about to be married.",
"an5.34": "The Buddha teaches General Sīha the benefits which he can see for himself in this life, and those in the next life, which he must take on faith.",
"an5.35": "Five benefits of generosity for lay people.",
"an5.36": "Gifts at the right time, in a appropriate way. The verses are the classic “kāladāna” blessing.",
"an5.37": "Give and you shall receive. The verses are a classic blessing, beginning with “Āyudo balado dhīro”.",
"an5.38": "When someone is a donor, the reap the benefits of association with the Saṅgha.",
"an5.39": "Reasons why parents want to have children.",
"an5.40": "How a virtuous family head is like a great tree in the mountains.",
"an5.41": "The legitimate purposes of wealth.",
"an5.42": "A good person brings many blessings to their family.",
"an5.43": "You don’t get good things by praying for them, but by how you live.",
"an5.44": "If you give the best, you get the best.",
"an5.45": "When offerings are used for deep meditation, the merit multiplies enormously.",
"an5.46": "Kinds of spiritual success, in brief.",
"an5.47": "Kinds of spiritual wealth, in detail.",
"an5.48": "A wise person reflects on their nature, so they do not suffer when struck by loss.",
"an5.49": "When King Pasenadi learns of the death of his beloved Queen Mallikā, the Buddha consoles him.",
"an5.50": "Depressed by the death of Queen Bhaddā, King Muṇḍa of Rājagaha neglects his duties, and broods by the side of his beloved’s corpse. Venerable Nārada eases his grief.",
"an5.51": "The five hindrances weaken wisdom like side-channels weaken a river’s flow.",
"an5.52": "The five hindrances are entirely unwholesome.",
"an5.53": "Conditions that help meditation progress smoothly.",
"an5.54": "Times that are supportive for meditation practice.",
"an5.55": "A mother and son, though ordained as monk and nun, have sexual relations. The Buddha launches a powerful attack on the dangers of sex.",
"an5.56": "A monk, dissatisfied with monastic life, seeks support from his mentor.",
"an5.57": "Topics that are worthy regularly reflecting on, whether as a lay person or renunciant.",
"an5.58": "When some wild young men show deep respect for the Buddha, a family elder is astonished.",
"an5.59": "Things that are hard to find in someone who has gone forth when old.",
"an5.60": "Things that are hard to find in someone who has gone forth when old.",
"an5.61": "Five meditations are very beneficial.",
"an5.62": "Five meditations lead to the deathless.",
"an5.63": "Noble growth for a male disciple.",
"an5.64": "Noble growth for a female disciple.",
"an5.65": "Qualifications for taking part in a discussion on Dharma.",
"an5.66": "Qualifications for sharing Dharma.",
"an5.67": "The four bases of psychic power, together with energy, lead to awakening.",
"an5.68": "The Buddha developed the bases for psychic power, which lead to his awakening.",
"an5.69": "Five meditations that lead to disillusionment with the world.",
"an5.70": "Five meditations that lead to the end of defilements.",
"an5.71": "Five meditations lead to freedom. The Buddha supplies five similes, which subtly illustrate five aspects of awakening.",
"an5.72": "Five meditations lead to freedom. The Buddha supplies five similes, which subtly illustrate five aspects of awakening.",
"an5.73": "The difference between someone who merely studies the letter of the Dharma, and someone who truly lives by it.",
"an5.74": "The difference between someone who merely studies the letter of the Dharma, and someone who truly lives by it.",
"an5.75": "Some warriors, like some monks, falter before the threat of battle, while others emerge victorious. ",
"an5.76": "Some warriors, like some monks, are killed or injured in battle, while others emerge victorious. ",
"an5.77": "The dangers of living in a wilderness among wild beasts and so on.",
"an5.78": "The uncertainties of life may prevent your practice.",
"an5.79": "When the teachers and leaders of the Saṅgha are not well practised, their weakness will be passed down the generations.",
"an5.80": "The Saṅgha may forsake the simple life and indulge in luxuries.",
"an5.81": "Senior mendicants with strong defilements are disliked.",
"an5.82": "Senior mendicants with strong defilements are disliked.",
"an5.83": "Senior mendicants who are manipulative and opportunistic are disliked.",
"an5.84": "Qualities making a senior mendicant liked or disliked.",
"an5.85": "A senior mendicant with no endurance is disliked.",
"an5.86": "A senior mendicant is like if they can analyse and explain the Dharma well, and if they are helpful in the monastery.",
"an5.87": "A senior mendicant with morality, learning, who is a good speaker and successful meditator is liked.",
"an5.88": "Even if a senior mendicant has many good qualities, they can still lead people astray if they have wrong view.",
"an5.89": "Even if a mendicant is a trainee, they won’t progress if they don’t focus on practice. In brief.",
"an5.90": "Even if a mendicant is a trainee, they won’t progress if they don’t focus on practice. In detail.",
"an5.91": "",
"an5.92": "",
"an5.93": "When people are asked whether they are enlightened, they might answer for different reasons.",
"an5.94": "Living comfortably by practising meditation.",
"an5.95": "The four aspects of textual analysis.",
"an5.96": "Supported by five factors, one who practises mindfulness of breathing will soon realize the unshakeable.",
"an5.97": "Supported by five factors, one who practises mindfulness of breathing will soon realize the unshakeable.",
"an5.98": "A lion is always respectful when it kills. So too when the Buddha teaches he always respects his audience. "
}
}
